services:
    mongo:
        image: mongo:focal
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: learngraphql
        volumes:
            - ./data/mongo:/data/db
